export const CLICKED_BUTTON_REQUEST = 'CLICKED_BUTTON_REQUEST';
export const CLICKED_BUTTON_SUCCESS = 'CLICKED_BUTTON_SUCCESS';
export const CLICKED_BUTTON_FAILURE = 'CLICKED_BUTTON_FAILURE';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
